# language: java
# tests: true
build:
    environment:
        java: 'java-8-oracle'
    nodes:
        analysis:
        tests:
            override:
                - java-scrutinizer-run
checks:
    java: true
    
    
    build:

filter:
    excluded_paths:
        - parser/src/main/**
