# language: java
# tests: true
checks:
    java: true
build:
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    -
                        command: java-sonar-run
                        use_website_config: true
            environment:
                docker:
                    remote_engine: true
filter:
    excluded_paths:
        - parser/src/main/**
