// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.file;

public interface Blob {
	// Blob
	/**
	 * @return
	 */
	public long getSize();

	/**
	 * @return
	 */
	public String getType();

	/**
	 * @param start
	 * @param length
	 * @return
	 */
	public Blob slice(long start, long length);

	/**
	 * @param start
	 * @param length
	 * @param contentType
	 * @return
	 */
	public Blob slice(long start, long length, String contentType);
}
