/* Generated By:JavaCC: Do not edit this line. SACParserCSS1Constants.java */
package com.steadystate.css.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SACParserCSS1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int S = 1;
  /** RegularExpression Id. */
  int IDENT = 3;
  /** RegularExpression Id. */
  int LINK_PSCLASS = 4;
  /** RegularExpression Id. */
  int VISITED_PSCLASS = 5;
  /** RegularExpression Id. */
  int ACTIVE_PSCLASS = 6;
  /** RegularExpression Id. */
  int FIRST_LINE = 7;
  /** RegularExpression Id. */
  int FIRST_LETTER = 8;
  /** RegularExpression Id. */
  int HASH = 9;
  /** RegularExpression Id. */
  int LBRACE = 10;
  /** RegularExpression Id. */
  int RBRACE = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int DOT = 13;
  /** RegularExpression Id. */
  int SEMICOLON = 14;
  /** RegularExpression Id. */
  int COLON = 15;
  /** RegularExpression Id. */
  int SLASH = 16;
  /** RegularExpression Id. */
  int PLUS = 17;
  /** RegularExpression Id. */
  int MINUS = 18;
  /** RegularExpression Id. */
  int EQUALS = 19;
  /** RegularExpression Id. */
  int GT = 20;
  /** RegularExpression Id. */
  int LSQUARE = 21;
  /** RegularExpression Id. */
  int RSQUARE = 22;
  /** RegularExpression Id. */
  int STRING = 23;
  /** RegularExpression Id. */
  int RROUND = 24;
  /** RegularExpression Id. */
  int URL = 25;
  /** RegularExpression Id. */
  int CDO = 26;
  /** RegularExpression Id. */
  int CDC = 27;
  /** RegularExpression Id. */
  int IMPORT_SYM = 28;
  /** RegularExpression Id. */
  int IMPORTANT_SYM = 29;
  /** RegularExpression Id. */
  int ATKEYWORD = 30;
  /** RegularExpression Id. */
  int EMS = 31;
  /** RegularExpression Id. */
  int EXS = 32;
  /** RegularExpression Id. */
  int LENGTH_PX = 33;
  /** RegularExpression Id. */
  int LENGTH_CM = 34;
  /** RegularExpression Id. */
  int LENGTH_MM = 35;
  /** RegularExpression Id. */
  int LENGTH_IN = 36;
  /** RegularExpression Id. */
  int LENGTH_PT = 37;
  /** RegularExpression Id. */
  int LENGTH_PC = 38;
  /** RegularExpression Id. */
  int PERCENTAGE = 39;
  /** RegularExpression Id. */
  int NUMBER = 40;
  /** RegularExpression Id. */
  int RGB = 41;
  /** RegularExpression Id. */
  int NAME = 42;
  /** RegularExpression Id. */
  int D = 43;
  /** RegularExpression Id. */
  int NUM = 44;
  /** RegularExpression Id. */
  int UNICODERANGE = 45;
  /** RegularExpression Id. */
  int RANGE = 46;
  /** RegularExpression Id. */
  int Q16 = 47;
  /** RegularExpression Id. */
  int Q15 = 48;
  /** RegularExpression Id. */
  int Q14 = 49;
  /** RegularExpression Id. */
  int Q13 = 50;
  /** RegularExpression Id. */
  int Q12 = 51;
  /** RegularExpression Id. */
  int Q11 = 52;
  /** RegularExpression Id. */
  int LATIN1 = 53;
  /** RegularExpression Id. */
  int NMCHAR = 54;
  /** RegularExpression Id. */
  int NMSTART = 55;
  /** RegularExpression Id. */
  int STRING1 = 56;
  /** RegularExpression Id. */
  int STRING2 = 57;
  /** RegularExpression Id. */
  int NONASCII = 58;
  /** RegularExpression Id. */
  int ESCAPE = 59;
  /** RegularExpression Id. */
  int NL = 60;
  /** RegularExpression Id. */
  int UNICODE = 61;
  /** RegularExpression Id. */
  int HNUM = 62;
  /** RegularExpression Id. */
  int H = 63;
  /** RegularExpression Id. */
  int UNKNOWN = 66;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<S>",
    "\"/*\"",
    "<IDENT>",
    "\":link\"",
    "\":visited\"",
    "\":active\"",
    "\":first-line\"",
    "\":first-letter\"",
    "<HASH>",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\":\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "\">\"",
    "\"[\"",
    "\"]\"",
    "<STRING>",
    "\")\"",
    "<URL>",
    "\"<!--\"",
    "\"-->\"",
    "\"@import\"",
    "<IMPORTANT_SYM>",
    "<ATKEYWORD>",
    "<EMS>",
    "<EXS>",
    "<LENGTH_PX>",
    "<LENGTH_CM>",
    "<LENGTH_MM>",
    "<LENGTH_IN>",
    "<LENGTH_PT>",
    "<LENGTH_PC>",
    "<PERCENTAGE>",
    "<NUMBER>",
    "\"rgb(\"",
    "<NAME>",
    "<D>",
    "<NUM>",
    "<UNICODERANGE>",
    "<RANGE>",
    "<Q16>",
    "<Q15>",
    "<Q14>",
    "<Q13>",
    "<Q12>",
    "\"?\"",
    "<LATIN1>",
    "<NMCHAR>",
    "<NMSTART>",
    "<STRING1>",
    "<STRING2>",
    "<NONASCII>",
    "<ESCAPE>",
    "<NL>",
    "<UNICODE>",
    "<HNUM>",
    "<H>",
    "\"*/\"",
    "<token of kind 65>",
    "<UNKNOWN>",
  };

}
