// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface AudioTrack {
	// AudioTrack
	public String getId();

	public String getKind();

	public String getLabel();

	public String getLanguage();

	public boolean getEnabled();

	public void setEnabled(boolean enabled);
}
