// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

import org.w3c.dom.Element;

public interface DOMElementMap {
	// DOMElementMap
	public String getElement(String name);

	public void setElement(String name, Element value);

	public void createElement(String name, Element value);

	public void deleteElement(String name);
}
