// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLUListElement extends HTMLElement {
	// HTMLUListElement
	// HTMLUListElement-33
	public boolean getCompact();

	public void setCompact(boolean compact);

	public String getType();

	public void setType(String type);
}
