// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLPreElement extends HTMLElement {
	// HTMLPreElement
	// HTMLPreElement-27
	public int getWidth();

	public void setWidth(int width);
}
