// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLBaseElement extends HTMLElement {
	// HTMLBaseElement
	public String getHref();

	public void setHref(String href);

	public String getTarget();

	public void setTarget(String target);
}
