// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLVideoElement extends HTMLMediaElement {
	// HTMLVideoElement
	public int getWidth();

	public void setWidth(int width);

	public int getHeight();

	public void setHeight(int height);

	public int getVideoWidth();

	public int getVideoHeight();

	public String getPoster();

	public void setPoster(String poster);
}
