// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

import org.w3c.dom.Node;

public interface HTMLOptionsCollection extends HTMLCollection {
	// HTMLOptionsCollection
	public int getLength();

	public void setLength(int length);

	public Node namedItem(String name);

	public void add(HTMLElement element);

	public void add(HTMLElement element, HTMLElement before);

	public void add(HTMLElement element, int before);

	public void remove(int index);

	public int getSelectedIndex();

	public void setSelectedIndex(int selectedIndex);
}
