// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLTableCaptionElement extends HTMLElement {
	// HTMLTableCaptionElement
	// HTMLTableCaptionElement-7
	public String getAlign();

	public void setAlign(String align);
}
