// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLOptionElement_Constructor {
	// Constructor
	public HTMLOptionElement createInstance();

	public HTMLOptionElement createInstance(String text);

	public HTMLOptionElement createInstance(String text, String value);

	public HTMLOptionElement createInstance(String text, String value, boolean defaultSelected);

	public HTMLOptionElement createInstance(String text, String value, boolean defaultSelected, boolean selected);
}
