// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

import org.w3c.dom.Node;

public interface HTMLFormControlsCollection extends HTMLCollection {
	// HTMLFormControlsCollection
	public Node namedItem(String name);
}
