// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLHRElement extends HTMLElement {
	// HTMLHRElement
	// HTMLHRElement-13
	public String getAlign();

	public void setAlign(String align);

	public String getColor();

	public void setColor(String color);

	public boolean getNoShade();

	public void setNoShade(boolean noShade);

	public String getSize();

	public void setSize(String size);

	public String getWidth();

	public void setWidth(String width);
}
