// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLTableColElement extends HTMLElement {
	// HTMLTableColElement
	public int getSpan();

	public void setSpan(int span);

	// HTMLTableColElement-8
	public String getAlign();

	public void setAlign(String align);

	public String getCh();

	public void setCh(String ch);

	public String getChOff();

	public void setChOff(String chOff);

	public String getVAlign();

	public void setVAlign(String vAlign);

	public String getWidth();

	public void setWidth(String width);
}
