// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLFontElement extends HTMLElement {
	// HTMLFontElement
	public String getColor();

	public void setColor(String color);

	public String getFace();

	public void setFace(String face);

	public String getSize();

	public void setSize(String size);
}
