// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLHeadingElement extends HTMLElement {
	// HTMLHeadingElement
	// HTMLHeadingElement-12
	public String getAlign();

	public void setAlign(String align);
}
