// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLFieldSetElement extends HTMLElement {
	// HTMLFieldSetElement
	public boolean getDisabled();

	public void setDisabled(boolean disabled);

	public HTMLFormElement getForm();

	public String getName();

	public void setName(String name);

	public String getType();

	public HTMLFormControlsCollection getElements();

	public boolean getWillValidate();

	public ValidityState getValidity();

	public String getValidationMessage();

	public boolean checkValidity();

	public void setCustomValidity(String error);
}
