// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLModElement extends HTMLElement {
	// HTMLModElement
	public String getCite();

	public void setCite(String cite);

	public String getDateTime();

	public void setDateTime(String dateTime);
}
