// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLLabelElement extends HTMLElement {
	// HTMLLabelElement
	public HTMLFormElement getForm();

	public String getHtmlFor();

	public void setHtmlFor(String htmlFor);

	public HTMLElement getControl();
}
