// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLLegendElement extends HTMLElement {
	// HTMLLegendElement
	public HTMLFormElement getForm();

	// HTMLLegendElement-18
	public String getAlign();

	public void setAlign(String align);
}
