// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLMetaElement extends HTMLElement {
	// HTMLMetaElement
	public String getName();

	public void setName(String name);

	public String getHttpEquiv();

	public void setHttpEquiv(String httpEquiv);

	public String getContent();

	public void setContent(String content);

	// HTMLMetaElement-22
	public String getScheme();

	public void setScheme(String scheme);
}
