// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLOListElement extends HTMLElement {
	// HTMLOListElement
	public boolean getReversed();

	public void setReversed(boolean reversed);

	public int getStart();

	public void setStart(int start);

	public String getType();

	public void setType(String type);

	// HTMLOListElement-24
	public boolean getCompact();

	public void setCompact(boolean compact);
}
