// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLBRElement extends HTMLElement {
	// HTMLBRElement
	// HTMLBRElement-6
	public String getClear();

	public void setClear(String clear);
}
