// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

import org.lobobrowser.w3c.file.FileCallback;

public interface HTMLCanvasElement extends HTMLElement {

	/** The fill. */
	int FILL = 0;

	/** The fill rect. */
	int FILL_RECT = 1;

	/** The fill text. */
	int FILL_TEXT = 2;

	/** The circle. */
	int CIRCLE = 3;

	/** The stroke. */
	int STROKE = 4;

	/** The stroke rect. */
	int STROKE_RECT = 5;

	/** The stroke text. */
	int STROKE_TEXT = 6;

	/** The rect. */
	int RECT = 7;

	/** The image. */
	int IMAGE = 8;

	/** The image clip. */
	int IMAGE_CLIP = 9;

	/** The clear rect. */
	int CLEAR_RECT = 10;

	// HTMLCanvasElement
	public int getWidth();

	public void setWidth(int width);

	public int getHeight();

	public void setHeight(int height);

	public String toDataURL();

	public String toDataURL(String type, Object... args);

	public void toBlob(FileCallback callback);

	public void toBlob(FileCallback callback, String type, Object... args);

	public Object getContext(String contextId);
}
