// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLMenuElement extends HTMLElement {
	// HTMLMenuElement
	public String getType();

	public void setType(String type);

	public String getLabel();

	public void setLabel(String label);

	// HTMLMenuElement-21
	public boolean getCompact();

	public void setCompact(boolean compact);
}
