// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLSourceElement extends HTMLElement {
	// HTMLSourceElement
	public String getSrc();

	public void setSrc(String src);

	public String getType();

	public void setType(String type);

	public String getMedia();

	public void setMedia(String media);
}
