// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLCommandElement extends HTMLElement {
	// HTMLCommandElement
	public String getType();

	public void setType(String type);

	@Override
	public String getLabel();

	public void setLabel(String label);

	@Override
	public String getIcon();

	public void setIcon(String icon);

	@Override
	public boolean getDisabled();

	public void setDisabled(boolean disabled);

	@Override
	public boolean getChecked();

	public void setChecked(boolean checked);

	public String getRadiogroup();

	public void setRadiogroup(String radiogroup);
}
