// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

import org.w3c.dom.Node;

public interface HTMLAllCollection extends HTMLCollection {
	// HTMLAllCollection
	public Node namedItem(String name);

	public HTMLAllCollection tags(String tagName);
}
