// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLImageElement_Constructor {
	// Constructor
	public HTMLImageElement createInstance();

	public HTMLImageElement createInstance(int width);

	public HTMLImageElement createInstance(int width, int height);
}
