// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLHeadElement extends HTMLElement {

	String getProfile();
	// HTMLHeadElement

	void setProfile(String profile);
}
