// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLDirectoryElement extends HTMLElement {
	// HTMLDirectoryElement
	public boolean getCompact();

	public void setCompact(boolean compact);
}
