// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLTimeElement extends HTMLElement {
	// HTMLTimeElement
	public String getDateTime();

	public void setDateTime(String dateTime);

	public boolean getPubDate();

	public void setPubDate(boolean pubDate);

	public long getValueAsDate();
}
