// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLMapElement extends HTMLElement {
	// HTMLMapElement
	public String getName();

	public void setName(String name);

	public HTMLCollection getAreas();

	public HTMLCollection getImages();
}
