// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLScriptElement extends HTMLElement {
	// HTMLScriptElement
	public String getSrc();

	public void setSrc(String src);

	public boolean getAsync();

	public void setAsync(boolean async);

	public boolean getDefer();

	public void setDefer(boolean defer);

	public String getType();

	public void setType(String type);

	public String getCharset();

	public void setCharset(String charset);

	public String getText();

	public void setText(String text);

	// HTMLScriptElement-28
	public String getEvent();

	public void setEvent(String event);

	public String getHtmlFor();

	public void setHtmlFor(String htmlFor);
}
