// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface HTMLLIElement extends HTMLElement {
	// HTMLLIElement
	public int getValue();

	public void setValue(int value);

	// HTMLLIElement-19
	public String getType();

	public void setType(String type);
}
