// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

public interface TextTrackCueList {
	// TextTrackCueList
	public int getLength();

	public TextTrackCue getElement(int index);

	public TextTrackCue getCueById(String id);
}
