// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

import org.mozilla.javascript.Function;
import org.w3c.dom.DocumentFragment;

public interface TextTrackCue {
	// TextTrackCue
	public TextTrack getTrack();

	public String getId();

	public double getStartTime();

	public double getEndTime();

	public boolean getPauseOnExit();

	public String getDirection();

	public boolean getSnapToLines();

	public int getLinePosition();

	public int getTextPosition();

	public int getSize();

	public String getAlignment();

	public String getCueAsSource();

	public DocumentFragment getCueAsHTML();

	public Function getOnenter();

	public void setOnenter(Function onenter);

	public Function getOnexit();

	public void setOnexit(Function onexit);
}
