// Generated by esidl 0.2.1.

package org.lobobrowser.w3c.html;

import org.mozilla.javascript.Function;

public interface VideoTrackList {
	// VideoTrackList
	public int getLength();

	public VideoTrack getElement(int index);

	public VideoTrack getTrackById(String id);

	public int getSelectedIndex();

	public Function getOnchange();

	public void setOnchange(Function onchange);
}
