// Generated by esidl (r1714).

package org.lobobrowser.w3c.xpath;

public class XPathException extends RuntimeException {
	public XPathException(short code, String message) {
		super(message);
		this.code = code;
	}

	public static final short INVALID_EXPRESSION_ERR = 51;
	public static final short TYPE_ERR = 52;
	public short code;
}
