// Generated by esidl (r1714).

package org.lobobrowser.w3c.xpath;

import org.w3c.dom.Element;
import org.w3c.dom.Node;

public interface XPathNamespace extends Node {
	// XPathNamespace
	public static final short XPATH_NAMESPACE_NODE = 13;

	public Element getOwnerElement();
}
