/* Generated By:JavaCC: Do not edit this line. CSS3ParserConstants.java */
package org.htmlunit.cssparser.parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CSS3ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int S = 1;
  /** RegularExpression Id. */
  int H = 5;
  /** RegularExpression Id. */
  int HNUM = 6;
  /** RegularExpression Id. */
  int NONASCII = 7;
  /** RegularExpression Id. */
  int UNICODE = 8;
  /** RegularExpression Id. */
  int ESCAPE = 9;
  /** RegularExpression Id. */
  int NMSTART = 10;
  /** RegularExpression Id. */
  int NMCHAR = 11;
  /** RegularExpression Id. */
  int NL = 12;
  /** RegularExpression Id. */
  int STRING1 = 13;
  /** RegularExpression Id. */
  int STRING2 = 14;
  /** RegularExpression Id. */
  int COMMENT_ = 15;
  /** RegularExpression Id. */
  int AND = 16;
  /** RegularExpression Id. */
  int NOT = 17;
  /** RegularExpression Id. */
  int ONLY = 18;
  /** RegularExpression Id. */
  int NUMBER = 19;
  /** RegularExpression Id. */
  int INHERIT = 20;
  /** RegularExpression Id. */
  int IDENT = 21;
  /** RegularExpression Id. */
  int NAME = 22;
  /** RegularExpression Id. */
  int NUM = 23;
  /** RegularExpression Id. */
  int STRING = 24;
  /** RegularExpression Id. */
  int URL = 25;
  /** RegularExpression Id. */
  int A_LETTER = 26;
  /** RegularExpression Id. */
  int C_LETTER = 27;
  /** RegularExpression Id. */
  int D_LETTER = 28;
  /** RegularExpression Id. */
  int E_LETTER = 29;
  /** RegularExpression Id. */
  int F_LETTER = 30;
  /** RegularExpression Id. */
  int G_LETTER = 31;
  /** RegularExpression Id. */
  int H_LETTER = 32;
  /** RegularExpression Id. */
  int I_LETTER = 33;
  /** RegularExpression Id. */
  int K_LETTER = 34;
  /** RegularExpression Id. */
  int L_LETTER = 35;
  /** RegularExpression Id. */
  int M_LETTER = 36;
  /** RegularExpression Id. */
  int N_LETTER = 37;
  /** RegularExpression Id. */
  int O_LETTER = 38;
  /** RegularExpression Id. */
  int P_LETTER = 39;
  /** RegularExpression Id. */
  int R_LETTER = 40;
  /** RegularExpression Id. */
  int S_LETTER = 41;
  /** RegularExpression Id. */
  int T_LETTER = 42;
  /** RegularExpression Id. */
  int U_LETTER = 43;
  /** RegularExpression Id. */
  int X_LETTER = 44;
  /** RegularExpression Id. */
  int Z_LETTER = 45;
  /** RegularExpression Id. */
  int CDO = 46;
  /** RegularExpression Id. */
  int CDC = 47;
  /** RegularExpression Id. */
  int INCLUDES = 48;
  /** RegularExpression Id. */
  int DASHMATCH = 49;
  /** RegularExpression Id. */
  int PREFIXMATCH = 50;
  /** RegularExpression Id. */
  int SUFFIXMATCH = 51;
  /** RegularExpression Id. */
  int SUBSTRINGMATCH = 52;
  /** RegularExpression Id. */
  int LBRACE = 53;
  /** RegularExpression Id. */
  int RBRACE = 54;
  /** RegularExpression Id. */
  int LROUND = 55;
  /** RegularExpression Id. */
  int RROUND = 56;
  /** RegularExpression Id. */
  int DOT = 57;
  /** RegularExpression Id. */
  int SEMICOLON = 58;
  /** RegularExpression Id. */
  int COLON = 59;
  /** RegularExpression Id. */
  int ASTERISK = 60;
  /** RegularExpression Id. */
  int SLASH = 61;
  /** RegularExpression Id. */
  int MINUS = 62;
  /** RegularExpression Id. */
  int EQUALS = 63;
  /** RegularExpression Id. */
  int LSQUARE = 64;
  /** RegularExpression Id. */
  int RSQUARE = 65;
  /** RegularExpression Id. */
  int PLUS = 66;
  /** RegularExpression Id. */
  int GREATER = 67;
  /** RegularExpression Id. */
  int TILDE = 68;
  /** RegularExpression Id. */
  int COMMA = 69;
  /** RegularExpression Id. */
  int HASH = 70;
  /** RegularExpression Id. */
  int IMPORT_SYM = 71;
  /** RegularExpression Id. */
  int PAGE_SYM = 72;
  /** RegularExpression Id. */
  int MEDIA_SYM = 73;
  /** RegularExpression Id. */
  int FONT_FACE_SYM = 74;
  /** RegularExpression Id. */
  int CHARSET_SYM = 75;
  /** RegularExpression Id. */
  int IMPORTANT_SYM = 76;
  /** RegularExpression Id. */
  int EMS = 77;
  /** RegularExpression Id. */
  int REM = 78;
  /** RegularExpression Id. */
  int EXS = 79;
  /** RegularExpression Id. */
  int CH = 80;
  /** RegularExpression Id. */
  int VW = 81;
  /** RegularExpression Id. */
  int VH = 82;
  /** RegularExpression Id. */
  int VMIN = 83;
  /** RegularExpression Id. */
  int VMAX = 84;
  /** RegularExpression Id. */
  int LENGTH_PX = 85;
  /** RegularExpression Id. */
  int LENGTH_CM = 86;
  /** RegularExpression Id. */
  int LENGTH_MM = 87;
  /** RegularExpression Id. */
  int LENGTH_IN = 88;
  /** RegularExpression Id. */
  int LENGTH_PT = 89;
  /** RegularExpression Id. */
  int LENGTH_PC = 90;
  /** RegularExpression Id. */
  int LENGTH_Q = 91;
  /** RegularExpression Id. */
  int ANGLE_DEG = 92;
  /** RegularExpression Id. */
  int ANGLE_RAD = 93;
  /** RegularExpression Id. */
  int ANGLE_GRAD = 94;
  /** RegularExpression Id. */
  int ANGLE_TURN = 95;
  /** RegularExpression Id. */
  int TIME_MS = 96;
  /** RegularExpression Id. */
  int TIME_S = 97;
  /** RegularExpression Id. */
  int FREQ_HZ = 98;
  /** RegularExpression Id. */
  int FREQ_KHZ = 99;
  /** RegularExpression Id. */
  int RESOLUTION_DPI = 100;
  /** RegularExpression Id. */
  int RESOLUTION_DPCM = 101;
  /** RegularExpression Id. */
  int PERCENTAGE = 102;
  /** RegularExpression Id. */
  int DIMENSION = 103;
  /** RegularExpression Id. */
  int H_PLACEHOLDER = 104;
  /** RegularExpression Id. */
  int UNICODE_RANGE = 105;
  /** RegularExpression Id. */
  int URI = 106;
  /** RegularExpression Id. */
  int FUNCTION_NOT = 107;
  /** RegularExpression Id. */
  int FUNCTION_LANG = 108;
  /** RegularExpression Id. */
  int FUNCTION_CALC = 109;
  /** RegularExpression Id. */
  int FUNCTION_VAR = 110;
  /** RegularExpression Id. */
  int FUNCTION_RGB = 111;
  /** RegularExpression Id. */
  int FUNCTION_HSL = 112;
  /** RegularExpression Id. */
  int CUSTOM_PROPERTY_NAME = 113;
  /** RegularExpression Id. */
  int FUNCTION = 114;
  /** RegularExpression Id. */
  int ATKEYWORD = 115;
  /** RegularExpression Id. */
  int UNKNOWN = 116;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<S>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 4>",
    "<H>",
    "<HNUM>",
    "<NONASCII>",
    "<UNICODE>",
    "<ESCAPE>",
    "<NMSTART>",
    "<NMCHAR>",
    "<NL>",
    "<STRING1>",
    "<STRING2>",
    "<COMMENT_>",
    "\"and\"",
    "\"not\"",
    "\"only\"",
    "<NUMBER>",
    "\"inherit\"",
    "<IDENT>",
    "<NAME>",
    "<NUM>",
    "<STRING>",
    "<URL>",
    "<A_LETTER>",
    "<C_LETTER>",
    "<D_LETTER>",
    "<E_LETTER>",
    "<F_LETTER>",
    "<G_LETTER>",
    "<H_LETTER>",
    "<I_LETTER>",
    "<K_LETTER>",
    "<L_LETTER>",
    "<M_LETTER>",
    "<N_LETTER>",
    "<O_LETTER>",
    "<P_LETTER>",
    "<R_LETTER>",
    "<S_LETTER>",
    "<T_LETTER>",
    "<U_LETTER>",
    "<X_LETTER>",
    "<Z_LETTER>",
    "\"<!--\"",
    "\"-->\"",
    "\"~=\"",
    "\"|=\"",
    "\"^=\"",
    "\"$=\"",
    "\"*=\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\";\"",
    "\":\"",
    "\"*\"",
    "\"/\"",
    "\"-\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\"+\"",
    "\">\"",
    "\"~\"",
    "\",\"",
    "<HASH>",
    "<IMPORT_SYM>",
    "<PAGE_SYM>",
    "<MEDIA_SYM>",
    "<FONT_FACE_SYM>",
    "<CHARSET_SYM>",
    "<IMPORTANT_SYM>",
    "<EMS>",
    "<REM>",
    "<EXS>",
    "<CH>",
    "<VW>",
    "<VH>",
    "<VMIN>",
    "<VMAX>",
    "<LENGTH_PX>",
    "<LENGTH_CM>",
    "<LENGTH_MM>",
    "<LENGTH_IN>",
    "<LENGTH_PT>",
    "<LENGTH_PC>",
    "<LENGTH_Q>",
    "<ANGLE_DEG>",
    "<ANGLE_RAD>",
    "<ANGLE_GRAD>",
    "<ANGLE_TURN>",
    "<TIME_MS>",
    "<TIME_S>",
    "<FREQ_HZ>",
    "<FREQ_KHZ>",
    "<RESOLUTION_DPI>",
    "<RESOLUTION_DPCM>",
    "<PERCENTAGE>",
    "<DIMENSION>",
    "<H_PLACEHOLDER>",
    "<UNICODE_RANGE>",
    "<URI>",
    "<FUNCTION_NOT>",
    "<FUNCTION_LANG>",
    "<FUNCTION_CALC>",
    "<FUNCTION_VAR>",
    "<FUNCTION_RGB>",
    "<FUNCTION_HSL>",
    "<CUSTOM_PROPERTY_NAME>",
    "<FUNCTION>",
    "<ATKEYWORD>",
    "<UNKNOWN>",
    "\"progid:\"",
  };

}
