/*
 * MIT License
 *
 * Copyright (c) 2014 - 2023 LoboEvolution
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * Contact info: ivan.difrancesco@yahoo.it
 */

package org.loboevolution.css;

import org.junit.Test;
import org.loboevolution.driver.LoboUnitTest;

/**
 * Tests for ComputedColorTest
 */
public class ComputedColorTest extends LoboUnitTest {


    @Test
    public void backgroundColor() {
        final String html = "<html><head>\n"
                + "<script>\n"
                + "  function test() {\n"
                + "    for (var i = 1; i <= 10; i++) {\n"
                + "    	var div = document.getElementById('p'+i);\n"
                + "    	var style = window.getComputedStyle(div, null);\n"
                + "    	alert(style.backgroundColor);\n"
                + "    }\n"
                + "  }\n"
                + "</script>\n"
                + "<style type=\"text/css\">\n"
                + "      #p1 { background-color: hsla(120, 75%, 50%); }\n"
                + "      #p2 { background-color: hsla(120.0, 75%, 50%); }\n"
                + "      #p3 { background-color: hsla(1.2e2, 75%, 50%); }\n"
                + "      #p4 { background-color: hsla(1.2E2, 75%, 50%); }\n"
                + "      #p5 { background-color: hsla(60, 75%, 50%); }\n"
                + "      #p6 { background-color: hsl(120, 75%, 50%, 0.2); }\n"
                + "      #p7 { background-color: hsl(120.0, 75%, 50%, 0.4); }\n"
                + "      #p8 { background-color: hsl(1.2e2, 75%, 50%, 0.6); }\n"
                + "      #p9 { background-color: hsl(1.2E2, 75%, 50%, 0.8); }\n"
                + "      #p10 { background-color: hsl(60.0, 75%, 50%, 1.0); }\n"
                + "    </style>"
                + "</head>\n"
                + "<body onload='test()'>   \n"
                + "   <p id='p1'>color</p>  \n"
                + "   <p id='p2'>color</p>  \n"
                + "   <p id='p3'>color</p>  \n"
                + "   <p id='p4'>color</p>  \n"
                + "   <p id='p5'>color</p>  \n"
                + "   <p id='p6'>color</p>  \n"
                + "   <p id='p7'>color</p>  \n"
                + "   <p id='p8'>color</p>  \n"
                + "   <p id='p9'>color</p>  \n"
                + "   <p id='p10'>color</p> \n"
                + "</body></hml>";
        final String[] messages = {"rgb(32, 223, 32)","rgb(32, 223, 32)","rgb(32, 223, 32)","rgb(32, 223, 32)",
                                   "rgb(223, 223, 32)","rgba(32, 223, 32, 0.2)","rgba(32, 223, 32, 0.4)",
                                   "rgba(32, 223, 32, 0.6)","rgba(32, 223, 32, 0.8)","rgb(223, 223, 32)"};
        checkHtmlAlert(html, messages);
    }

    @Test
    public void backgroundColor2() {
        final String html = "<html><head>\n"
                + "<script>\n"
                + "  function test() {\n"
                + "    for (var i = 1; i <= 10; i++) {\n"
                + "    	var div = document.getElementById('p'+i);\n"
                + "    	var style = window.getComputedStyle(div, null);\n"
                + "    	alert(style.backgroundColor);\n"
                + "    }\n"
                + "  }\n"
                + "</script>\n"
                + "<style type=\"text/css\">\n"
                + "        #p1 { background-color: hsl(120, 75%, 50%, 0.2);} \n"
                + "        #p2 { background-color: hsl(120, 75%, 50%, 40%);} \n"
                + "        #p3 { background-color: hsl(120 75% 50% / 0.6);} \n"
                + "        #p4 { background-color: hsl(120 75% 50% / 80%);} \n"
                + "        #p5 { background-color: hsl(120 75% 50%/1.0);} \n"
                + "        #p6 { background-color: hsl(120 75% 50%/100%);} \n"
                + "        #p7 { background-color: hsl(120, 75%, 50%,1.0);} \n"
                + "        #p8 { background-color: hsl(120, 75%, 50%,100%);} \n"
                + "        #p9 { background-color: hsl(120 75% 50%);} \n"
                + "        #p10 { background-color: hsl(120 ,75%, 50%);} \n"
                + "    </style>"
                + "</head>\n"
                + "<body onload='test()'>   \n"
                + "   <p id='p1'>color</p>  \n"
                + "   <p id='p2'>color</p>  \n"
                + "   <p id='p3'>color</p>  \n"
                + "   <p id='p4'>color</p>  \n"
                + "   <p id='p5'>color</p>  \n"
                + "   <p id='p6'>color</p>  \n"
                + "   <p id='p7'>color</p>  \n"
                + "   <p id='p8'>color</p>  \n"
                + "   <p id='p9'>color</p>  \n"
                + "   <p id='p10'>color</p> \n"
                + "</body></hml>";
        final String[] messages = {"rgba(32, 223, 32, 0.2)","rgba(32, 223, 32, 0.4)","rgba(32, 223, 32, 0.6)",
                                   "rgba(32, 223, 32, 0.8)","rgb(32, 223, 32)","rgb(32, 223, 32)","rgb(32, 223, 32)",
                                    "rgb(32, 223, 32)","rgb(32, 223, 32)","rgb(32, 223, 32)"};
        checkHtmlAlert(html, messages);
    }

    @Test
    public void colorName() {
        final String html = "<html><head>\n"
                + "<script>\n"
                + "  function test() {\n"
                + "    for (var i = 1; i <= 148; i++) {\n"
                + "    	var div = document.getElementById('p'+i);\n"
                + "    	var style = window.getComputedStyle(div, null);\n"
                + "    	alert(style.backgroundColor);\n"
                + "    }\n"
                + "  }\n"
                + "</script>\n"
                + "<style type=\"text/css\">\n"
                + "        #p1 { background-color: transparent;} \n"
                + "        #p2 { background-color: aliceblue;} \n"
                + "        #p3 { background-color: antiquewhite;} \n"
                + "        #p4 { background-color: aqua;} \n"
                + "        #p5 { background-color: aquamarine;} \n"
                + "        #p6 { background-color: azure;} \n"
                + "        #p7 { background-color: beige;} \n"
                + "        #p8 { background-color: bisque;} \n"
                + "        #p9 { background-color: black;} \n"
                + "        #p10 { background-color: blanchedalmond;} \n"
                + "        #p11 { background-color: blue;} \n"
                + "        #p12 { background-color: blueviolet;} \n"
                + "        #p13 { background-color: brown;} \n"
                + "        #p14 { background-color: burlywood;} \n"
                + "        #p15 { background-color: cadetblue;} \n"
                + "        #p16 { background-color: chartreuse;} \n"
                + "        #p17 { background-color: chocolate;} \n"
                + "        #p18 { background-color: coral;} \n"
                + "        #p19 { background-color: cornflowerblue;} \n"
                + "        #p20 { background-color: cornsilk;} \n"
                + "        #p21 { background-color: crimson;} \n"
                + "        #p22 { background-color: cyan;} \n"
                + "        #p23 { background-color: darkblue;} \n"
                + "        #p24 { background-color: darkcyan;} \n"
                + "        #p25 { background-color: darkgoldenrod;} \n"
                + "        #p26 { background-color: darkgray;} \n"
                + "        #p27 { background-color: darkgreen;} \n"
                + "        #p28 { background-color: darkgrey;} \n"
                + "        #p29 { background-color: darkkhaki;} \n"
                + "        #p30 { background-color: darkmagenta;} \n"
                + "        #p31 { background-color: darkolivegreen;} \n"
                + "        #p32 { background-color: darkorange;} \n"
                + "        #p33 { background-color: darkorchid;} \n"
                + "        #p34 { background-color: darkred;} \n"
                + "        #p35 { background-color: darksalmon;} \n"
                + "        #p36 { background-color: darkseagreen;} \n"
                + "        #p37 { background-color: darkslateblue;} \n"
                + "        #p38 { background-color: darkslategray;} \n"
                + "        #p39 { background-color: darkslategrey;} \n"
                + "        #p40 { background-color: darkturquoise;} \n"
                + "        #p41 { background-color: darkviolet;} \n"
                + "        #p42 { background-color: deeppink;} \n"
                + "        #p43 { background-color: deepskyblue;} \n"
                + "        #p44 { background-color: dimgray;} \n"
                + "        #p45 { background-color: dimgrey;} \n"
                + "        #p46 { background-color: dodgerblue;} \n"
                + "        #p47 { background-color: firebrick;} \n"
                + "        #p48 { background-color: floralwhite;} \n"
                + "        #p49 { background-color: forestgreen;} \n"
                + "        #p50 { background-color: fuchsia;} \n"
                + "        #p51 { background-color: gainsboro;} \n"
                + "        #p52 { background-color: ghostwhite;} \n"
                + "        #p53 { background-color: gold;} \n"
                + "        #p54 { background-color: goldenrod;} \n"
                + "        #p55 { background-color: gray;} \n"
                + "        #p56 { background-color: green;} \n"
                + "        #p57 { background-color: greenyellow;} \n"
                + "        #p58 { background-color: grey;} \n"
                + "        #p59 { background-color: honeydew;} \n"
                + "        #p60 { background-color: hotpink;} \n"
                + "        #p61 { background-color: indianred;} \n"
                + "        #p62 { background-color: indigo;} \n"
                + "        #p63 { background-color: ivory;} \n"
                + "        #p64 { background-color: khaki;} \n"
                + "        #p65 { background-color: lavender;} \n"
                + "        #p66 { background-color: lavenderblush;} \n"
                + "        #p67 { background-color: lawngreen;} \n"
                + "        #p68 { background-color: lemonchiffon;} \n"
                + "        #p69 { background-color: lightblue;} \n"
                + "        #p70 { background-color: lightcoral;} \n"
                + "        #p71 { background-color: lightcyan;} \n"
                + "        #p72 { background-color: lightgoldenrodyellow;} \n"
                + "        #p73 { background-color: lightgray;} \n"
                + "        #p74 { background-color: lightgreen;} \n"
                + "        #p75 { background-color: lightgrey;} \n"
                + "        #p76 { background-color: lightpink;} \n"
                + "        #p77 { background-color: lightsalmon;} \n"
                + "        #p78 { background-color: lightseagreen;} \n"
                + "        #p79 { background-color: lightskyblue;} \n"
                + "        #p80 { background-color: lightslategray;} \n"
                + "        #p81 { background-color: lightslategrey;} \n"
                + "        #p82 { background-color: lightsteelblue;} \n"
                + "        #p83 { background-color: lightyellow;} \n"
                + "        #p84 { background-color: lime;} \n"
                + "        #p85 { background-color: limegreen;} \n"
                + "        #p86 { background-color: linen;} \n"
                + "        #p87 { background-color: magenta;} \n"
                + "        #p88 { background-color: maroon;} \n"
                + "        #p89 { background-color: mediumaquamarine;} \n"
                + "        #p90 { background-color: mediumblue;} \n"
                + "        #p91 { background-color: mediumorchid;} \n"
                + "        #p92 { background-color: mediumpurple;} \n"
                + "        #p93 { background-color: mediumseagreen;} \n"
                + "        #p94 { background-color: mediumslateblue;} \n"
                + "        #p95 { background-color: mediumspringgreen;} \n"
                + "        #p96 { background-color: mediumturquoise;} \n"
                + "        #p97 { background-color: mediumvioletred;} \n"
                + "        #p98 { background-color: midnightblue;} \n"
                + "        #p99 { background-color: mintcream;} \n"
                + "        #p100 { background-color: mistyrose;} \n"
                + "        #p101 { background-color: moccasin;} \n"
                + "        #p102 { background-color: navajowhite;} \n"
                + "        #p103 { background-color: navy;} \n"
                + "        #p104 { background-color: oldlace;} \n"
                + "        #p105 { background-color: olive;} \n"
                + "        #p106 { background-color: olivedrab;} \n"
                + "        #p107 { background-color: orange;} \n"
                + "        #p108 { background-color: orangered;} \n"
                + "        #p109 { background-color: orchid;} \n"
                + "        #p110 { background-color: palegoldenrod;} \n"
                + "        #p111 { background-color: palegreen;} \n"
                + "        #p112 { background-color: paleturquoise;} \n"
                + "        #p113 { background-color: palevioletred;} \n"
                + "        #p114 { background-color: papayawhip;} \n"
                + "        #p115 { background-color: peachpuff;} \n"
                + "        #p116 { background-color: peru;} \n"
                + "        #p117 { background-color: pink;} \n"
                + "        #p118 { background-color: plum;} \n"
                + "        #p119 { background-color: powderblue;} \n"
                + "        #p120 { background-color: purple;} \n"
                + "        #p121 { background-color: red;} \n"
                + "        #p122 { background-color: rosybrown;} \n"
                + "        #p123 { background-color: royalblue;} \n"
                + "        #p124 { background-color: saddlebrown;} \n"
                + "        #p125 { background-color: salmon;} \n"
                + "        #p126 { background-color: sandybrown;} \n"
                + "        #p127 { background-color: seagreen;} \n"
                + "        #p128 { background-color: seashell;} \n"
                + "        #p129 { background-color: sienna;} \n"
                + "        #p130 { background-color: silver;} \n"
                + "        #p131 { background-color: skyblue;} \n"
                + "        #p132 { background-color: slateblue;} \n"
                + "        #p133 { background-color: slategray;} \n"
                + "        #p134 { background-color: slategrey;} \n"
                + "        #p135 { background-color: snow;} \n"
                + "        #p136 { background-color: springgreen;} \n"
                + "        #p137 { background-color: steelblue;} \n"
                + "        #p138 { background-color: tan;} \n"
                + "        #p139 { background-color: teal;} \n"
                + "        #p140 { background-color: thistle;} \n"
                + "        #p141 { background-color: tomato;} \n"
                + "        #p142 { background-color: turquoise;} \n"
                + "        #p143 { background-color: violet;} \n"
                + "        #p144 { background-color: wheat;} \n"
                + "        #p145 { background-color: white;} \n"
                + "        #p146 { background-color: whitesmoke;} \n"
                + "        #p147 { background-color: yellow;} \n"
                + "        #p148 { background-color: yellowgreen;} \n"
                + "    </style>"
                + "</head>\n"
                + "<body onload='test()'>   \n"
                + " <p id='p1'>color</p>  \n"
                + " <p id='p2'>color</p>  \n"
                + " <p id='p3'>color</p>  \n"
                + " <p id='p4'>color</p>  \n"
                + " <p id='p5'>color</p>  \n"
                + " <p id='p6'>color</p>  \n"
                + " <p id='p7'>color</p>  \n"
                + " <p id='p8'>color</p>  \n"
                + " <p id='p9'>color</p>  \n"
                + " <p id='p10'>color</p>  \n"
                + " <p id='p11'>color</p>  \n"
                + " <p id='p12'>color</p>  \n"
                + " <p id='p13'>color</p>  \n"
                + " <p id='p14'>color</p>  \n"
                + " <p id='p15'>color</p>  \n"
                + " <p id='p16'>color</p>  \n"
                + " <p id='p17'>color</p>  \n"
                + " <p id='p18'>color</p>  \n"
                + " <p id='p19'>color</p>  \n"
                + " <p id='p20'>color</p>  \n"
                + " <p id='p21'>color</p>  \n"
                + " <p id='p22'>color</p>  \n"
                + " <p id='p23'>color</p>  \n"
                + " <p id='p24'>color</p>  \n"
                + " <p id='p25'>color</p>  \n"
                + " <p id='p26'>color</p>  \n"
                + " <p id='p27'>color</p>  \n"
                + " <p id='p28'>color</p>  \n"
                + " <p id='p29'>color</p>  \n"
                + " <p id='p30'>color</p>  \n"
                + " <p id='p31'>color</p>  \n"
                + " <p id='p32'>color</p>  \n"
                + " <p id='p33'>color</p>  \n"
                + " <p id='p34'>color</p>  \n"
                + " <p id='p35'>color</p>  \n"
                + " <p id='p36'>color</p>  \n"
                + " <p id='p37'>color</p>  \n"
                + " <p id='p38'>color</p>  \n"
                + " <p id='p39'>color</p>  \n"
                + " <p id='p40'>color</p>  \n"
                + " <p id='p41'>color</p>  \n"
                + " <p id='p42'>color</p>  \n"
                + " <p id='p43'>color</p>  \n"
                + " <p id='p44'>color</p>  \n"
                + " <p id='p45'>color</p>  \n"
                + " <p id='p46'>color</p>  \n"
                + " <p id='p47'>color</p>  \n"
                + " <p id='p48'>color</p>  \n"
                + " <p id='p49'>color</p>  \n"
                + " <p id='p50'>color</p>  \n"
                + " <p id='p51'>color</p>  \n"
                + " <p id='p52'>color</p>  \n"
                + " <p id='p53'>color</p>  \n"
                + " <p id='p54'>color</p>  \n"
                + " <p id='p55'>color</p>  \n"
                + " <p id='p56'>color</p>  \n"
                + " <p id='p57'>color</p>  \n"
                + " <p id='p58'>color</p>  \n"
                + " <p id='p59'>color</p>  \n"
                + " <p id='p60'>color</p>  \n"
                + " <p id='p61'>color</p>  \n"
                + " <p id='p62'>color</p>  \n"
                + " <p id='p63'>color</p>  \n"
                + " <p id='p64'>color</p>  \n"
                + " <p id='p65'>color</p>  \n"
                + " <p id='p66'>color</p>  \n"
                + " <p id='p67'>color</p>  \n"
                + " <p id='p68'>color</p>  \n"
                + " <p id='p69'>color</p>  \n"
                + " <p id='p70'>color</p>  \n"
                + " <p id='p71'>color</p>  \n"
                + " <p id='p72'>color</p>  \n"
                + " <p id='p73'>color</p>  \n"
                + " <p id='p74'>color</p>  \n"
                + " <p id='p75'>color</p>  \n"
                + " <p id='p76'>color</p>  \n"
                + " <p id='p77'>color</p>  \n"
                + " <p id='p78'>color</p>  \n"
                + " <p id='p79'>color</p>  \n"
                + " <p id='p80'>color</p>  \n"
                + " <p id='p81'>color</p>  \n"
                + " <p id='p82'>color</p>  \n"
                + " <p id='p83'>color</p>  \n"
                + " <p id='p84'>color</p>  \n"
                + " <p id='p85'>color</p>  \n"
                + " <p id='p86'>color</p>  \n"
                + " <p id='p87'>color</p>  \n"
                + " <p id='p88'>color</p>  \n"
                + " <p id='p89'>color</p>  \n"
                + " <p id='p90'>color</p>  \n"
                + " <p id='p91'>color</p>  \n"
                + " <p id='p92'>color</p>  \n"
                + " <p id='p93'>color</p>  \n"
                + " <p id='p94'>color</p>  \n"
                + " <p id='p95'>color</p>  \n"
                + " <p id='p96'>color</p>  \n"
                + " <p id='p97'>color</p>  \n"
                + " <p id='p98'>color</p>  \n"
                + " <p id='p99'>color</p>  \n"
                + " <p id='p100'>color</p>  \n"
                + " <p id='p101'>color</p>  \n"
                + " <p id='p102'>color</p>  \n"
                + " <p id='p103'>color</p>  \n"
                + " <p id='p104'>color</p>  \n"
                + " <p id='p105'>color</p>  \n"
                + " <p id='p106'>color</p>  \n"
                + " <p id='p107'>color</p>  \n"
                + " <p id='p108'>color</p>  \n"
                + " <p id='p109'>color</p>  \n"
                + " <p id='p110'>color</p>  \n"
                + " <p id='p111'>color</p>  \n"
                + " <p id='p112'>color</p>  \n"
                + " <p id='p113'>color</p>  \n"
                + " <p id='p114'>color</p>  \n"
                + " <p id='p115'>color</p>  \n"
                + " <p id='p116'>color</p>  \n"
                + " <p id='p117'>color</p>  \n"
                + " <p id='p118'>color</p>  \n"
                + " <p id='p119'>color</p>  \n"
                + " <p id='p120'>color</p>  \n"
                + " <p id='p121'>color</p>  \n"
                + " <p id='p122'>color</p>  \n"
                + " <p id='p123'>color</p>  \n"
                + " <p id='p124'>color</p>  \n"
                + " <p id='p125'>color</p>  \n"
                + " <p id='p126'>color</p>  \n"
                + " <p id='p127'>color</p>  \n"
                + " <p id='p128'>color</p>  \n"
                + " <p id='p129'>color</p>  \n"
                + " <p id='p130'>color</p>  \n"
                + " <p id='p131'>color</p>  \n"
                + " <p id='p132'>color</p>  \n"
                + " <p id='p133'>color</p>  \n"
                + " <p id='p134'>color</p>  \n"
                + " <p id='p135'>color</p>  \n"
                + " <p id='p136'>color</p>  \n"
                + " <p id='p137'>color</p>  \n"
                + " <p id='p138'>color</p>  \n"
                + " <p id='p139'>color</p>  \n"
                + " <p id='p140'>color</p>  \n"
                + " <p id='p141'>color</p>  \n"
                + " <p id='p142'>color</p>  \n"
                + " <p id='p143'>color</p>  \n"
                + " <p id='p144'>color</p>  \n"
                + " <p id='p145'>color</p>  \n"
                + " <p id='p146'>color</p>  \n"
                + " <p id='p147'>color</p>  \n"
                + " <p id='p148'>color</p>  \n"
                + "</body></hml>";
        final String[] messages = { "rgb(0, 0, 0)", "rgb(240, 248, 255)", "rgb(250, 235, 215)", "rgb(0, 255, 255)",
                                    "rgb(127, 255, 212)", "rgb(240, 255, 255)", "rgb(245, 245, 220)", "rgb(255, 228, 196)",
                                    "rgb(0, 0, 0)", "rgb(255, 235, 205)", "rgb(0, 0, 255)", "rgb(138, 43, 226)", "rgb(165, 42, 42)",
                                    "rgb(222, 184, 135)", "rgb(95, 158, 160)", "rgb(127, 255, 0)", "rgb(210, 105, 30)", "rgb(255, 127, 80)",
                                    "rgb(100, 149, 237)", "rgb(255, 248, 220)", "rgb(220, 20, 60)", "rgb(0, 255, 255)", "rgb(0, 0, 139)",
                                    "rgb(0, 139, 139)", "rgb(184, 134, 11)", "rgb(169, 169, 169)", "rgb(0, 100, 0)", "rgb(169, 169, 169)",
                                    "rgb(189, 183, 107)", "rgb(139, 0, 139)", "rgb(85, 107, 47)", "rgb(255, 140, 0)", "rgb(153, 50, 204)",
                                    "rgb(139, 0, 0)", "rgb(233, 150, 122)", "rgb(143, 188, 143)", "rgb(72, 61, 139)", "rgb(47, 79, 79)",
                                    "rgb(47, 79, 79)", "rgb(0, 206, 209)", "rgb(148, 0, 211)", "rgb(255, 20, 147)", "rgb(0, 191, 255)",
                                    "rgb(105, 105, 105)", "rgb(105, 105, 105)", "rgb(30, 144, 255)", "rgb(178, 34, 34)", "rgb(255, 250, 240)", "rgb(34, 139, 34)",
                                    "rgb(255, 0, 255)", "rgb(220, 220, 220)", "rgb(248, 248, 255)", "rgb(255, 215, 0)", "rgb(218, 165, 32)", "rgb(128, 128, 128)",
                                    "rgb(0, 128, 0)", "rgb(173, 255, 47)", "rgb(128, 128, 128)", "rgb(240, 255, 240)", "rgb(255, 105, 180)", "rgb(205, 92, 92)",
                                    "rgb(75, 0, 130)", "rgb(255, 255, 240)", "rgb(240, 230, 140)", "rgb(230, 230, 250)", "rgb(255, 240, 245)", "rgb(124, 252, 0)",
                                    "rgb(255, 250, 205)", "rgb(173, 216, 230)", "rgb(240, 128, 128)", "rgb(224, 255, 255)", "rgb(250, 250, 210)", "rgb(211, 211, 211)",
                                    "rgb(144, 238, 144)", "rgb(211, 211, 211)", "rgb(255, 182, 193)", "rgb(255, 160, 122)", "rgb(32, 178, 170)", "rgb(135, 206, 250)",
                                    "rgb(119, 136, 153)", "rgb(119, 136, 153)", "rgb(176, 196, 222)", "rgb(255, 255, 224)", "rgb(0, 255, 0)", "rgb(50, 205, 50)",
                                    "rgb(250, 240, 230)", "rgb(255, 0, 255)", "rgb(128, 0, 0)", "rgb(102, 205, 170)", "rgb(0, 0, 205)", "rgb(186, 85, 211)",
                                    "rgb(147, 112, 219)", "rgb(60, 179, 113)", "rgb(123, 104, 238)", "rgb(0, 250, 154)", "rgb(72, 209, 204)", "rgb(199, 21, 133)",
                                    "rgb(25, 25, 112)", "rgb(245, 255, 250)", "rgb(255, 228, 225)", "rgb(255, 228, 181)", "rgb(255, 222, 173)", "rgb(0, 0, 128)",
                                    "rgb(253, 245, 230)", "rgb(128, 128, 0)", "rgb(107, 142, 35)", "rgb(255, 165, 0)", "rgb(255, 69, 0)", "rgb(218, 112, 214)",
                                    "rgb(238, 232, 170)", "rgb(152, 251, 152)", "rgb(175, 238, 238)", "rgb(219, 112, 147)", "rgb(255, 239, 213)", "rgb(255, 218, 185)",
                                    "rgb(205, 133, 63)", "rgb(255, 192, 203)", "rgb(221, 160, 221)", "rgb(176, 224, 230)", "rgb(128, 0, 128)", "rgb(255, 0, 0)",
                                    "rgb(188, 143, 143)", "rgb(65, 105, 225)", "rgb(139, 69, 19)", "rgb(250, 128, 114)", "rgb(244, 164, 96)", "rgb(46, 139, 87)",
                                    "rgb(255, 245, 238)", "rgb(160, 82, 45)", "rgb(192, 192, 192)", "rgb(135, 206, 235)", "rgb(106, 90, 205)", "rgb(112, 128, 144)",
                                    "rgb(112, 128, 144)", "rgb(255, 250, 250)", "rgb(0, 255, 127)", "rgb(70, 130, 180)", "rgb(210, 180, 140)", "rgb(0, 128, 128)",
                                    "rgb(216, 191, 216)", "rgb(255, 99, 71)", "rgb(64, 224, 208)", "rgb(238, 130, 238)", "rgb(245, 222, 179)", "rgb(255, 255, 255)",
                                    "rgb(245, 245, 245)", "rgb(255, 255, 0)", "rgb(154, 205, 50)"};
        checkHtmlAlert(html, messages);
    }
}
